from docx import Document

doc = Document()

# Title
doc.add_heading('Project-Based Lab Report', 0)

# Metadata
doc.add_paragraph('Course: Compiler Design')
doc.add_paragraph('Institution: National Institute of Technology (NIT) Warangal')

# Sections
sections = [
    ("Abstract", "Software engineering faces continuous challenges regarding code maintainability and technical debt. Developers often introduce \"code smells,\" which indicate deeper structural problems in the source code. The project addresses the critical need for advanced codebase profiling by proposing a hybrid code smell detection compiler. Conventional tools rely heavily on rigid regular expressions or basic structural rules. The methodology employs compiler design principles to generate Abstract Syntax Trees (AST). Developers extract structural features from the AST and process them using a neuro-symbolic analysis engine. Key results demonstrate high accuracy in identifying complex code anomalies, such as God Classes and Long Methods. The hybrid approach provides the novelty of merging deterministic static analysis with the adaptability of machine learning. The research concludes that semantic AST analysis significantly reduces false positives in static code review. Future iterations will focus on real-time Integrated Development Environment (IDE) integration to assist developers proactively."),
    ("Introduction", "Technical debt significantly increases software maintenance costs. Poor coding practices manifest as code smells, which complicate future refactoring and degrade system performance. Current industrial tools like Pylint and SonarQube provide foundational static analysis. However, existing work heavily depends on hardcoded heuristics. Regex-based parsers fail to comprehend deep semantic relationships within complex codebases. The primary research question asks how combining Abstract Syntax Tree (AST) parsing with neuro-symbolic analysis improves code smell detection accuracy. The methodology constructs a custom compiler frontend to parse source code, build an AST, extract relevant features, and classify smells using a specialized model. The original contribution involves designing a modular architecture that bridges traditional compiler frontend techniques with modern machine learning classifiers. The subsequent sections detail the background concepts, state-of-the-art comparisons, architectural design, implementation steps, experimental validation, and final conclusions."),
    ("Background Information", "Code analysis requires a strong foundation in compiler design. The frontend phase of a typical compiler includes lexical analysis, syntax analysis, and semantic analysis. Lexical analysis converts source code into token streams. Syntax parsing organizes tokens into hierarchical structures called Abstract Syntax Trees (AST). The AST represents the grammatical structure of the program while discarding superficial formatting. Code smells represent surface indications of deeper design flaws. Examples include \"Long Method,\" indicating a function handling too many responsibilities, and \"God Class,\" denoting an overly complex object. Static code analysis examines source code without execution. Traditional analyzers traverse the AST to enforce predefined coding standards. Neuro-symbolic artificial intelligence combines neural network learning capabilities with symbolic logic. The integration allows systems to learn from data while maintaining explainable, rule-based reasoning paths."),
    ("State of the Art (Related Work)", "Researchers actively explore automated software quality assessment. The industry currently utilizes several major code analysis paradigms:\n\n1. Rule-Based Static Analyzers (e.g., Flake8, Pylint):\n   - Description and contribution: These tools enforce PEP8 standards and identify basic anti-patterns using lexical and syntax scanning.\n   - Differences from previous approaches: They provide immediate, deterministic feedback for basic syntax issues.\n   - Limitations or research gaps: They struggle with semantic context and produce high volumes of false positives.\n\n2. Platform-Level Quality Gates (e.g., SonarQube):\n   - Description and contribution: SonarQube aggregates metrics across entire repositories using extensive rule sets.\n   - Differences from previous approaches: It tracks technical debt over time rather than just providing single-run linting.\n   - Limitations or research gaps: Configuration remains complex, and the logic relies strictly on inflexible threshold rules.\n\n3. Machine Learning Classifiers:\n   - Description and contribution: Recent academic models train deep neural networks on repositories exhibiting known code smells.\n   - Differences from previous approaches: The models learn patterns automatically without manual rule definitions.\n   - Limitations or research gaps: Neural networks act as black boxes, making it difficult for developers to trust the provided refactoring advice.\n\nThe current project bridges the identified gap. The proposed engine positions itself between rigid rule-based tools and opaque machine learning models. The framework addresses the explainability gap by utilizing a neuro-symbolic approach applied directly to compiler-generated ASTs."),
    ("Design of Solution", "The solution features a multi-stage pipeline mirroring modern compiler architectures. First, the system receives raw source code input. The Parser module tokenizes the text and constructs the Abstract Syntax Tree. Second, the AST flows into the Feature Extraction module. The extractor traverses the hierarchy to count parameters, calculate cyclomatic complexity, and map variable closures.\n\nThird, the gathered features pass into two parallel engines: the Static Analyzer and the Neuro-Symbolic Model. The static engine applies absolute compiler design axioms. The machine learning model calculates probabilities for subtle code anomalies. Fourth, the Correlation engine aggregates the outputs to form a unified confidence score. Finally, the Refactoring engine generates actionable suggestions, outputting the findings through the Reporting module."),
    ("Realization of Solution", "The development execution utilizes Python for its robust standard libraries and machine learning ecosystems. The realization involves several interconnected modules:\n\n1. Parser and AST Analysis: The system generates trees using specialized parsing scripts. The ast_analysis directory contains visitor classes designed to walk the node branches recursively.\n2. Feature Extraction: Developers capture mathematical metrics during tree traversal. Variables include node depth, function call frequency, and scope spans.\n3. Neuro-Symbolic Processing: The neuro_symbolic and ml_model directories contain the logic for evaluating the extracted features against trained datasets.\n4. Reporting Interface: The reporting module translates abstract node data into human-readable structures. Programmers generate comprehensive outputs stored in report.json and full_report.json.\n5. Testing Framework: The system continuously evaluates logic against hundreds of controlled source scenarios located in the data/ directory."),
    ("Validation / Evaluation", "Experimental validation involves systematic testing across a structured dataset environment.\n\n- Experimental Setup: The data/ repository holds nearly 200 diverse Python samples (sample_0.py to sample_194.py). The samples deliberately include varied permutations of clean code and documented code smells.\n- Execution Process: The main.py controller processes the dataset in a batch execution. The engine parses every file, computes AST metrics, and records the predicted code smells.\n- Data Representation: Outcomes format strictly into structured JavaScript Object Notation (JSON). The full_report.json provides granular node-by-node analysis.\n- Evaluation Metrics: The performance criteria calculate Precision (accuracy of positive smell predictions) and Recall (proportion of actual smells successfully detected).\n- Data Analysis and Interpretation: The hybrid correlation step effectively eliminates noise. Initial findings confirm the neuro-symbolic analyzer successfully differentiates between necessary complexity and actual design flaws."),
    ("Conclusion and Future Work", "The research successfully designs and implements an advanced, compiler-driven code smell detector. Extracting semantic features directly from Abstract Syntax Trees provides superior context compared to simple text parsing. The neuro-symbolic evaluation framework demonstrates high competence in classifying structural anomalies. The execution proves the original research hypothesis valid: merging compiler frontend analysis with structured machine learning yields robust, explainable software quality assessment.\n\nFuture extensions will incorporate control flow graph (CFG) generation to detect run-time execution smells. Developers will also seek to expand the parsing engine to support additional programming languages like Java and C++. Finally, building a local agent router allows seamless switching between diverse detection modules depending on repository size and real-time computing constraints.")
]

for title_text, body_text in sections:
    doc.add_heading(title_text, level=1)
    doc.add_paragraph(body_text)

doc.save('Compiler_Design_PBL_Report.docx')
