
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND EQUALS GT GTE ID LT LTE NUMBER OR RULEstatements : statements statement\n| statementstatement : RULE ID EQUALS expressionexpression : expression AND conditionexpression : expression OR conditionexpression : conditioncondition : ID GT NUMBERcondition : ID LT NUMBERcondition : ID GTE NUMBERcondition : ID LTE NUMBER'
    
_lr_action_items = {'RULE':([0,1,2,4,8,9,16,17,18,19,20,21,],[3,3,-2,-1,-3,-6,-7,-8,-9,-10,-4,-5,]),'$end':([1,2,4,8,9,16,17,18,19,20,21,],[0,-2,-1,-3,-6,-7,-8,-9,-10,-4,-5,]),'ID':([3,6,14,15,],[5,7,7,7,]),'EQUALS':([5,],[6,]),'GT':([7,],[10,]),'LT':([7,],[11,]),'GTE':([7,],[12,]),'LTE':([7,],[13,]),'AND':([8,9,16,17,18,19,20,21,],[14,-6,-7,-8,-9,-10,-4,-5,]),'OR':([8,9,16,17,18,19,20,21,],[15,-6,-7,-8,-9,-10,-4,-5,]),'NUMBER':([10,11,12,13,],[16,17,18,19,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statements':([0,],[1,]),'statement':([0,1,],[2,4,]),'expression':([6,],[8,]),'condition':([6,14,15,],[9,20,21,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statements","S'",1,None,None,None),
  ('statements -> statements statement','statements',2,'p_statements_multiple','dsl_parser.py',62),
  ('statements -> statement','statements',1,'p_statements_multiple','dsl_parser.py',63),
  ('statement -> RULE ID EQUALS expression','statement',4,'p_statement_rule','dsl_parser.py',67),
  ('expression -> expression AND condition','expression',3,'p_expression_and','dsl_parser.py',73),
  ('expression -> expression OR condition','expression',3,'p_expression_or','dsl_parser.py',77),
  ('expression -> condition','expression',1,'p_expression_single','dsl_parser.py',81),
  ('condition -> ID GT NUMBER','condition',3,'p_condition_gt','dsl_parser.py',85),
  ('condition -> ID LT NUMBER','condition',3,'p_condition_lt','dsl_parser.py',90),
  ('condition -> ID GTE NUMBER','condition',3,'p_condition_gte','dsl_parser.py',95),
  ('condition -> ID LTE NUMBER','condition',3,'p_condition_lte','dsl_parser.py',100),
]
